### ISSUE TITLE
Does this SDK support these graphs?

### ISSUE THREAD

**Issue by chennaranganath965** [vojtamolda/Plotly.swift#19]
I need to implement all these graphs in my Application. 

Column Chart
Line Chart
Combined Chart
 Bubble Map, 
 Point Map, 
 Choropleth Map

is this SDK supports all the graphs which i've mentioned ?

Thanks in Advance..!

**Comment by vojtamolda** [comment]
Hello @chennaranganath965,

Yes. You can create all these charts using Plotly. Here's link to the documentation: https://vojtamolda.github.io/Plotly.swift/. It's easy to get overwhelmed by the number of attributes each plot has but there's a nice trick - if you want to find simple examples check out the unit test directory. It mimics the JavaScript version so you can check how the plot looks like by following the links there.

Also, I'm assuming that by the Combined you mean Column + Line Chart in one axis system.

Cheers,

  Vojta

**Comment by vojtamolda** [comment]
By the way, what kind of a project do you plan to do?
